### PR TITLE
Enhances branch name support

### PR DESCRIPTION
**Pull request by Xav83**
As described by the [Coveralls documentation](https://docs.coveralls.io/supported-ci-services), we can use CI_BRANCH to specify the branch on which the coverage is performed.

### CODE REVIEW

**Comment by Xav83** [comment]
Hi @eddyxu,

it seems that the test scripts runned on Travis have some problem.
Indeed, they either end up with this line:
```
error: Setup script exited with Sorry, Python 3.4 or newer required
```
or has some errors probably due to the old version of python used.

May I suggest to upgrade the version of [Python](https://www.python.org/downloads/) used in those tests ?

**Comment by eddyxu** [comment]
yes, please.

Target python version to 3.7+ seems to be approprite.

We should migrate to github action sometime later though.

**Comment by Xav83** [comment]
Just to be exhaustive, this means modifying the tests to support `3.7`, `3.8` and `3.9`, and drop the support for `2.7`, `pypy`, `3.4` and `3.5`.

Capture

@eddyxu I don't know the contribution policy on this project, so I can either modify the `travis.yml` in this Pull Request or create a new Pull Request that only fixes the `travis.yml` file. 🙂

**Comment by Xav83** [comment]
@eddyxu, I have fixed the tests on Travis by specifying the version of some python packages to use (`requests` and `idna`), on this Pull Request 😉

**Review by eddyxu — APPROVED** [review]
LGTM. Thanks @Xav83 !

**Pull request merged**
