### PR TITLE
issue #80 updating README with new help output

### PR DESCRIPTION
**Pull request by mkfifo**

### CODE REVIEW

**Comment by mkfifo** [comment]
This PR now deals with both issue #80 and #82

**Comment by mkfifo** [comment]
removing second commit as it broke the testing script

**Comment by mkfifo** [comment]
Second attempt at resolving issue #82 nicely

**Comment by mkfifo** [comment]
I have pushed a few more commits that are refactoring changes and should have no functional changes, they were partially based on the output of landscape.io

**Comment by mkfifo** [comment]
Some more tidy up commits to try improve our landscape.io code health and make the code easier to understand.

Sorry for all the noise at once, please let me know if I can improve anything.

**Comment by mkfifo** [comment]
This gets us to 100% code health, there is still 1 stylistic error but it is minor (and was not introduced by me)

**Comment by mkfifo** [comment]
I have removed any changes that touch issue #82

**Comment by eddyxu** [comment]
Cool changes! Thanks @mkfifo

**Pull request merged**
