### PR TITLE
Bug fix: Using max_cov_count with integer typecast

### PR DESCRIPTION
**Pull request by sumedhghaisas**
Sorry for this bug.

### CODE REVIEW

**Comment by myint** [comment]
I think it would be better to fix it by simply adding `type=int` rather than casting things afterwards:

```python
    parser.add_argument('--max-cov-count', metavar='NUMBER', type=int,
```

**Comment by sumedhghaisas** [comment]
ohh... that does sound better. Pardon my ignorance... new to python :) I will change it...

**Comment by eddyxu** [comment]
Sorry for late to the game. And thanks a lot for the fix!

**Comment by myint** [comment]
@eddyxu Did you mean to merge this rather than close it? It looks like it got closed, but I don't see a change to `coverage.py`.

**Comment by eddyxu** [comment]
@myint Yea, my fault. Merged it.

**Pull request merged**
